<?PHP

/* Do not edit this file */

$this->options['requestfilter'] = "";
$this->options['filterlong'] = "";
$this->options['filterxss'] = "";
$this->options['filtersql'] = "";
$this->options['filterprefix'] = "";
$this->options['filtertruncation'] = "";
$this->options['filterfiles'] = "";
$this->options['throw404'] = "";
$this->options['filterlog'] = "";
$this->options['strongpass'] = "";
$this->options['norealerror'] = "";
$this->options['customerror'] = "";
$this->options['loginjs'] = "";
$this->options['bruteforce'] = "";
$this->options['maxattempts'] = "";
$this->options['lockout'] = "";
$this->options['keeplog'] = "";
$this->options['lockoutmessage'] = "";
$this->options['tarpit'] = "";
$this->options['maxtimeout'] = "";
